site_name: UI Tools文档
nav:
    - 主页: index.md
    - 使用说明 1.0: user-guide-1.0.md
    - 网页版CHANGELOG: WEB-CHANGELOG.md
    - 程序版CHANGELOG: APP-CHANGELOG.md
dev_addr: 127.0.0.1:8888
use_directory_urls: false
theme:
  name: 'material'
  language: 'zh'
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: true