site_name: UI Tools文档
nav:
    - 主页: index.md
    - 使用说明 1.0: user-guide-1.0.md
    - 构建及部署: build-and-deploy.md
    - 网页版CHANGELOG: WEB-CHANGELOG.md
    - 程序版CHANGELOG: APP-CHANGELOG.md
    - 样式主题制作器CHANGLOG: THEMES-CHANGELOG.md
    - FAQs: FAQs.md
dev_addr: 127.0.0.1:8888
use_directory_urls: false
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'indigo'
    accent: 'indigo'
markdown_extensions:
  - footnotes
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tasklist:
     custom_checkbox: true
  - admonition
  - toc:
      permalink: true
repo_name: 'UI-Builder'
repo_url: 'https://github.com/iwangbowen/UI-Builder'
edit_uri: 'edit/master/docs/'